import './globals.css'
import { Roboto } from 'next/font/google'

const font = Roboto({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'StockLib',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
